# Generated by Django 5.2.6 on 2026-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_email_business_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
