# Generated by Django 5.2.6 on 2026-02-12 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_is_rejected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='additional_docs',
            field=models.FileField(blank=True, help_text='Additional supporting documents (optional)', null=True, upload_to='vendor_docs/additional/'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Single Business Permit from County Government', null=True, upload_to='vendor_docs/permits/'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_registration_cert',
            field=models.FileField(blank=True, help_text='Certificate of Business Registration/BRS (PDF or Image)', null=True, upload_to='vendor_docs/registration/'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail Shop'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('service', 'Service Provider'), ('restaurant', 'Restaurant/Food'), ('electronics', 'Electronics'), ('fashion', 'Fashion/Clothing'), ('agriculture', 'Agriculture/Fresh Produce'), ('other', 'Other')], default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='documents_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='business',
            name='documents_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='kra_certificate',
            field=models.FileField(blank=True, help_text='KRA PIN Certificate (PDF or Image)', null=True, upload_to='vendor_docs/kra/'),
        ),
        migrations.AddField(
            model_name='business',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='KRA PIN (e.g., P012345678B)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_id_back',
            field=models.ImageField(blank=True, help_text='National ID Back Image', null=True, upload_to='vendor_docs/id_back/'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_id_front',
            field=models.ImageField(blank=True, help_text='National ID Front Image', null=True, upload_to='vendor_docs/id_front/'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_id_number',
            field=models.CharField(blank=True, help_text='National ID/Passport Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='permit_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_compliance_cert',
            field=models.FileField(blank=True, help_text='Tax Compliance Certificate (PDF or Image)', null=True, upload_to='vendor_docs/tax/'),
        ),
        migrations.AddField(
            model_name='business',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification decision', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='verification_status',
            field=models.CharField(choices=[('pending', '⏳ Pending Verification'), ('under_review', '📋 Under Review'), ('verified', '✅ Verified'), ('rejected', '❌ Rejected'), ('info_needed', 'ℹ️ More Info Needed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
