# Generated by Django 6.0.2 on 2026-03-02 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_business_additional_docs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='business',
            name='county',
            field=models.CharField(blank=True, help_text='County (e.g., Nairobi, Mombasa, Kisumu)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='delivery_radius',
            field=models.FloatField(default=10.0, help_text='Maximum delivery distance in kilometers'),
        ),
        migrations.AddField(
            model_name='business',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easier finding', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Vendor's location latitude (e.g., -1.286389 for Nairobi)", null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Vendor's location longitude (e.g., 36.817223 for Nairobi)", null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='show_exact_location',
            field=models.BooleanField(default=False, help_text='Show exact location on map or just approximate area'),
        ),
        migrations.AddField(
            model_name='business',
            name='sub_county',
            field=models.CharField(blank=True, help_text='Sub-county/Constituency', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='ward',
            field=models.CharField(blank=True, help_text='Ward/Location', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['county', 'verification_status'], name='accounts_bu_county_440160_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['latitude', 'longitude'], name='accounts_bu_latitud_869001_idx'),
        ),
    ]
