# Generated by Django 6.0.2 on 2026-03-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_business_options_business_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='formatted_address',
            field=models.TextField(blank=True, help_text='Full formatted address from geocoding service', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='geocoding_attempts',
            field=models.IntegerField(default=0, help_text='Number of geocoding attempts'),
        ),
        migrations.AddField(
            model_name='business',
            name='last_geocoded_at',
            field=models.DateTimeField(blank=True, help_text='When this business was last geocoded', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Maps Place ID for accurate location', max_length=255, null=True),
        ),
    ]
